/**
 * @file export configs
 */

export * from './vue'
export * from './yml'
export * from './html'
export * from './node'
export * from './pnpm'
export * from './sort'
export * from './svgo'
export * from './test'
export * from './toml'
export * from './antfu'
export * from './jsdoc'
export * from './jsonc'
export * from './ntnyq'
export * from './pinia'
export * from './depend'
export * from './format'
export * from './regexp'
export * from './unocss'
export * from './command'
export * from './ignores'
export * from './importX'
export * from './unicorn'
export * from './deMorgan'
export * from './markdown'
export * from './prettier'
export * from './specials'
export * from './gitignore'
export * from './javascript'
export * from './typescript'
export * from './eslintPlugin'
export * from './githubAction'
export * from './perfectionist'
export * from './unusedImports'
export * from './eslintComments'
