import type { TypedConfigItem } from '../types'

export const sortPackageJson = (): TypedConfigItem[] => [
  {
    name: 'ntnyq/sort/package-json',
    files: ['**/package.json'],
    rules: {
      'jsonc/sort-keys': [
        'error',
        {
          pathPattern: '^$',
          order: [
            'publisher',
            'name',
            'displayName',
            'preview',
            'type',
            'version',
            'private',
            'packageManager',
            'description',
            'keywords',
            'license',
            'author',
            'homepage',
            'repository',
            'funding',
            'exports',
            'main',
            'module',
            'unpkg',
            'jsdelivr',
            // workaround for `type: "module"` with TS `moduleResolution: "node16"`
            'types',
            'typesVersions',
            'bin',
            'icon',
            'files',
            'sideEffects',
            'scripts',
            'peerDependencies',
            'peerDependenciesMeta',
            'dependencies',
            'optionalDependencies',
            'devDependencies',
            'activationEvents',
            'contributes',
            'categories',
            'engines',
            'pnpm',
            'overrides',
            'resolutions',
            'husky',
            'prettier',
            'nano-staged',
            'lint-staged',
            'eslintConfig',
          ],
        },
        {
          pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies(Meta)?$',
          order: { type: 'asc' },
        },
        {
          order: { type: 'asc' },
          pathPattern: '^(?:resolutions|overrides|pnpm.overrides)$',
        },
        {
          pathPattern: '^exports.*$',
          order: ['types', 'import', 'require', 'default'],
        },
        {
          pathPattern: '^scripts$',
          order: { type: 'asc' },
        },
        {
          order: [
            // client hooks only
            'pre-commit',
            'prepare-commit-msg',
            'commit-msg',
            'post-commit',
            'pre-rebase',
            'post-rewrite',
            'post-checkout',
            'post-merge',
            'pre-push',
            'pre-auto-gc',
          ],
          pathPattern: '^(?:gitHooks|husky|simple-git-hooks)$',
        },
      ],
      'jsonc/sort-array-values': [
        'error',
        {
          pathPattern: '^files$',
          order: { type: 'asc' },
        },
      ],
    },
  },
]

export const sortTsConfig = (): TypedConfigItem[] => [
  {
    name: 'ntnyq/sort/tsconfig',
    files: ['**/tsconfig.json', '**/tsconfig.*.json'],
    rules: {
      'jsonc/sort-keys': [
        'error',
        {
          order: ['extends', 'compilerOptions', 'references', 'files', 'include', 'exclude'],
          pathPattern: '^$',
        },
        {
          order: [
            /* Projects */
            'incremental',
            'composite',
            'tsBuildInfoFile',
            'disableSourceOfProjectReferenceRedirect',
            'disableSolutionSearching',
            'disableReferencedProjectLoad',
            /* Language and Environment */
            'target',
            'lib',
            'jsx',
            'experimentalDecorators',
            'emitDecoratorMetadata',
            'jsxFactory',
            'jsxFragmentFactory',
            'jsxImportSource',
            'reactNamespace',
            'noLib',
            'useDefineForClassFields',
            'moduleDetection',
            /* Modules */
            'module',
            'rootDir',
            'moduleResolution',
            'baseUrl',
            'paths',
            'rootDirs',
            'typeRoots',
            'types',
            'allowUmdGlobalAccess',
            'moduleSuffixes',
            'allowImportingTsExtensions',
            'resolvePackageJsonExports',
            'resolvePackageJsonImports',
            'customConditions',
            'resolveJsonModule',
            'allowArbitraryExtensions',
            'noResolve',
            /* JavaScript Support */
            'allowJs',
            'checkJs',
            'maxNodeModuleJsDepth',
            /* Emit */
            'declaration',
            'declarationMap',
            'emitDeclarationOnly',
            'sourceMap',
            'inlineSourceMap',
            'outFile',
            'outDir',
            'removeComments',
            'noEmit',
            'importHelpers',
            'importsNotUsedAsValues',
            'downlevelIteration',
            'sourceRoot',
            'mapRoot',
            'inlineSources',
            'emitBOM',
            'newLine',
            'stripInternal',
            'noEmitHelpers',
            'noEmitOnError',
            'preserveConstEnums',
            'declarationDir',
            'preserveValueImports',
            /* Interop Constraints */
            'isolatedModules',
            'verbatimModuleSyntax',
            'allowSyntheticDefaultImports',
            'esModuleInterop',
            'preserveSymlinks',
            'forceConsistentCasingInFileNames',
            /* Type Checking */
            'strict',
            'strictBindCallApply',
            'strictFunctionTypes',
            'strictNullChecks',
            'strictPropertyInitialization',
            'allowUnreachableCode',
            'allowUnusedLabels',
            'alwaysStrict',
            'exactOptionalPropertyTypes',
            'noFallthroughCasesInSwitch',
            'noImplicitAny',
            'noImplicitOverride',
            'noImplicitReturns',
            'noImplicitThis',
            'noPropertyAccessFromIndexSignature',
            'noUncheckedIndexedAccess',
            'noUnusedLocals',
            'noUnusedParameters',
            'useUnknownInCatchVariables',
            /* Completeness */
            'skipDefaultLibCheck',
            'skipLibCheck',
          ],
          pathPattern: '^compilerOptions$',
        },
      ],
    },
  },
]

export const sortI18nLocale = (): TypedConfigItem[] => [
  {
    name: 'ntnyq/sort/i18n-locale',
    files: ['**/{locales,i18n}/*.json', '**/{locales,i18n}/*.y?(a)ml'],
    rules: {
      'jsonc/sort-keys': [
        'error',
        {
          pathPattern: '.*',
          order: { type: 'asc' },
        },
      ],
    },
  },
]
